name: Build and Upload C++ Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile metro.cpp
        run: g++ metro.cpp -o metro

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: metro-executable
          path: ./metro
